### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by luxuriant777**

### CODE REVIEW

**Review by sbublinskyi — APPROVED** [review]
its good, but I recommend you to add annotations for methods, for example:
def print_name(self) -> None

**Comment by Nattalli** [comment]
> its good, but I recommend you to add annotations for methods, for example: def print_name(self) -> None

You are right, type annotation is required. So you have to add them or your mentor will not approve these changes

**Comment by luxuriant777** [comment]
type annotations were added

**Review by Nattalli — APPROVED** [review]
👍🏻

**Pull request closed without merging**
